# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CQL3D_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2281, 1651)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.checkBox_RF = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_RF.setGeometry(QtCore.QRect(30, 1380, 145, 33))
        self.checkBox_RF.setObjectName("checkBox_RF")
        self.checkBox_NBI = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_NBI.setGeometry(QtCore.QRect(30, 1460, 161, 33))
        self.checkBox_NBI.setObjectName("checkBox_NBI")
        self.label_Basic_Plasma_Parameters = QtWidgets.QLabel(self.centralwidget)
        self.label_Basic_Plasma_Parameters.setGeometry(QtCore.QRect(30, 30, 331, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Basic_Plasma_Parameters.setFont(font)
        self.label_Basic_Plasma_Parameters.setObjectName("label_Basic_Plasma_Parameters")
        self.label_Electrons = QtWidgets.QLabel(self.centralwidget)
        self.label_Electrons.setGeometry(QtCore.QRect(30, 80, 111, 29))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_Electrons.setFont(font)
        self.label_Electrons.setObjectName("label_Electrons")
        self.lineEdit_electron_core_temperature = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_electron_core_temperature.setGeometry(QtCore.QRect(280, 130, 113, 35))
        self.lineEdit_electron_core_temperature.setObjectName("lineEdit_electron_core_temperature")
        self.label_electron_core_temperature = QtWidgets.QLabel(self.centralwidget)
        self.label_electron_core_temperature.setGeometry(QtCore.QRect(30, 130, 201, 29))
        self.label_electron_core_temperature.setObjectName("label_electron_core_temperature")
        self.lineEdit_electron_edge_temperature = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_electron_edge_temperature.setGeometry(QtCore.QRect(280, 180, 113, 35))
        self.lineEdit_electron_edge_temperature.setObjectName("lineEdit_electron_edge_temperature")
        self.label_electron_edge_temperature = QtWidgets.QLabel(self.centralwidget)
        self.label_electron_edge_temperature.setGeometry(QtCore.QRect(30, 180, 201, 29))
        self.label_electron_edge_temperature.setObjectName("label_electron_edge_temperature")
        self.label_electron_keV_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_electron_keV_1.setGeometry(QtCore.QRect(400, 130, 103, 29))
        self.label_electron_keV_1.setObjectName("label_electron_keV_1")
        self.label_electron_keV_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_electron_keV_2.setGeometry(QtCore.QRect(400, 180, 103, 29))
        self.label_electron_keV_2.setObjectName("label_electron_keV_2")
        self.lineEdit_electron_edge_density = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_electron_edge_density.setGeometry(QtCore.QRect(280, 280, 113, 35))
        self.lineEdit_electron_edge_density.setObjectName("lineEdit_electron_edge_density")
        self.label_electron_cm3_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_electron_cm3_2.setGeometry(QtCore.QRect(400, 280, 103, 29))
        self.label_electron_cm3_2.setObjectName("label_electron_cm3_2")
        self.label_electron_edge_density = QtWidgets.QLabel(self.centralwidget)
        self.label_electron_edge_density.setGeometry(QtCore.QRect(30, 280, 201, 29))
        self.label_electron_edge_density.setObjectName("label_electron_edge_density")
        self.lineEdit_electron_core_density = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_electron_core_density.setGeometry(QtCore.QRect(280, 230, 113, 35))
        self.lineEdit_electron_core_density.setObjectName("lineEdit_electron_core_density")
        self.label_electron_core_density = QtWidgets.QLabel(self.centralwidget)
        self.label_electron_core_density.setGeometry(QtCore.QRect(30, 230, 201, 29))
        self.label_electron_core_density.setObjectName("label_electron_core_density")
        self.label_electron_cm3_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_electron_cm3_1.setGeometry(QtCore.QRect(400, 230, 103, 29))
        self.label_electron_cm3_1.setObjectName("label_electron_cm3_1")
        self.lineEdit_ion_1_edge_density = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ion_1_edge_density.setGeometry(QtCore.QRect(280, 610, 113, 35))
        self.lineEdit_ion_1_edge_density.setObjectName("lineEdit_ion_1_edge_density")
        self.lineEdit_ion_1_edge_temperature = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ion_1_edge_temperature.setGeometry(QtCore.QRect(280, 510, 113, 35))
        self.lineEdit_ion_1_edge_temperature.setObjectName("lineEdit_ion_1_edge_temperature")
        self.label_ion_1_keV_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_1_keV_2.setGeometry(QtCore.QRect(400, 510, 103, 29))
        self.label_ion_1_keV_2.setObjectName("label_ion_1_keV_2")
        self.label_ion_1_cm3_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_1_cm3_1.setGeometry(QtCore.QRect(400, 560, 103, 29))
        self.label_ion_1_cm3_1.setObjectName("label_ion_1_cm3_1")
        self.lineEdit_ion_1_core_density = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ion_1_core_density.setGeometry(QtCore.QRect(280, 560, 113, 35))
        self.lineEdit_ion_1_core_density.setObjectName("lineEdit_ion_1_core_density")
        self.label_Ion_Species_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_Ion_Species_1.setGeometry(QtCore.QRect(30, 360, 161, 29))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_Ion_Species_1.setFont(font)
        self.label_Ion_Species_1.setObjectName("label_Ion_Species_1")
        self.label_ion_1_core_density = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_1_core_density.setGeometry(QtCore.QRect(30, 560, 201, 29))
        self.label_ion_1_core_density.setObjectName("label_ion_1_core_density")
        self.label_ion_1_edge_temperature = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_1_edge_temperature.setGeometry(QtCore.QRect(30, 510, 201, 29))
        self.label_ion_1_edge_temperature.setObjectName("label_ion_1_edge_temperature")
        self.label_ion_1_cm3_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_1_cm3_2.setGeometry(QtCore.QRect(400, 610, 103, 29))
        self.label_ion_1_cm3_2.setObjectName("label_ion_1_cm3_2")
        self.lineEdit_ion_1_core_temperature = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ion_1_core_temperature.setGeometry(QtCore.QRect(280, 460, 113, 35))
        self.lineEdit_ion_1_core_temperature.setObjectName("lineEdit_ion_1_core_temperature")
        self.label_ion_1_core_temperature = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_1_core_temperature.setGeometry(QtCore.QRect(30, 460, 201, 29))
        self.label_ion_1_core_temperature.setObjectName("label_ion_1_core_temperature")
        self.label_ion_1_keV_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_1_keV_1.setGeometry(QtCore.QRect(400, 460, 103, 29))
        self.label_ion_1_keV_1.setObjectName("label_ion_1_keV_1")
        self.label_ion_1_edge_density = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_1_edge_density.setGeometry(QtCore.QRect(30, 610, 201, 29))
        self.label_ion_1_edge_density.setObjectName("label_ion_1_edge_density")
        self.checkBox_ion_1_dist_func = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_ion_1_dist_func.setGeometry(QtCore.QRect(280, 360, 331, 33))
        self.checkBox_ion_1_dist_func.setObjectName("checkBox_ion_1_dist_func")
        self.label_ion_1_species_name = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_1_species_name.setGeometry(QtCore.QRect(30, 410, 201, 29))
        self.label_ion_1_species_name.setObjectName("label_ion_1_species_name")
        self.lineEdit_ion_2_core_temperature = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ion_2_core_temperature.setGeometry(QtCore.QRect(280, 790, 113, 35))
        self.lineEdit_ion_2_core_temperature.setObjectName("lineEdit_ion_2_core_temperature")
        self.checkBox_ion_2_dist_func = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_ion_2_dist_func.setGeometry(QtCore.QRect(500, 690, 331, 33))
        self.checkBox_ion_2_dist_func.setObjectName("checkBox_ion_2_dist_func")
        self.lineEdit_ion_2_core_density = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ion_2_core_density.setGeometry(QtCore.QRect(280, 890, 113, 35))
        self.lineEdit_ion_2_core_density.setObjectName("lineEdit_ion_2_core_density")
        self.label_ion_2_species_name = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_2_species_name.setGeometry(QtCore.QRect(30, 740, 201, 29))
        self.label_ion_2_species_name.setObjectName("label_ion_2_species_name")
        self.label_ion_2_core_density = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_2_core_density.setGeometry(QtCore.QRect(30, 890, 201, 29))
        self.label_ion_2_core_density.setObjectName("label_ion_2_core_density")
        self.label_ion_2_keV_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_2_keV_2.setGeometry(QtCore.QRect(400, 840, 103, 29))
        self.label_ion_2_keV_2.setObjectName("label_ion_2_keV_2")
        self.lineEdit_ion_2_edge_density = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ion_2_edge_density.setGeometry(QtCore.QRect(280, 940, 113, 35))
        self.lineEdit_ion_2_edge_density.setObjectName("lineEdit_ion_2_edge_density")
        self.label_ion_2_cm3_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_2_cm3_1.setGeometry(QtCore.QRect(400, 890, 103, 29))
        self.label_ion_2_cm3_1.setObjectName("label_ion_2_cm3_1")
        self.label_Ion_Species_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_Ion_Species_2.setGeometry(QtCore.QRect(30, 690, 161, 29))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_Ion_Species_2.setFont(font)
        self.label_Ion_Species_2.setObjectName("label_Ion_Species_2")
        self.lineEdit_ion_2_edge_temperature = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ion_2_edge_temperature.setGeometry(QtCore.QRect(280, 840, 113, 35))
        self.lineEdit_ion_2_edge_temperature.setObjectName("lineEdit_ion_2_edge_temperature")
        self.label_ion_2_edge_density = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_2_edge_density.setGeometry(QtCore.QRect(30, 940, 201, 29))
        self.label_ion_2_edge_density.setObjectName("label_ion_2_edge_density")
        self.label_ion_2_core_temperature = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_2_core_temperature.setGeometry(QtCore.QRect(30, 790, 201, 29))
        self.label_ion_2_core_temperature.setObjectName("label_ion_2_core_temperature")
        self.label_ion_2_edge_temperature = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_2_edge_temperature.setGeometry(QtCore.QRect(30, 840, 201, 29))
        self.label_ion_2_edge_temperature.setObjectName("label_ion_2_edge_temperature")
        self.label_ion_2_cm3_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_2_cm3_2.setGeometry(QtCore.QRect(400, 940, 103, 29))
        self.label_ion_2_cm3_2.setObjectName("label_ion_2_cm3_2")
        self.label_ion_2_keV_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_2_keV_1.setGeometry(QtCore.QRect(400, 790, 103, 29))
        self.label_ion_2_keV_1.setObjectName("label_ion_2_keV_1")
        self.checkBox_ion_2_disable = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_ion_2_disable.setGeometry(QtCore.QRect(280, 690, 211, 33))
        self.checkBox_ion_2_disable.setObjectName("checkBox_ion_2_disable")
        self.checkBox_ion_3_dist_func = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_ion_3_dist_func.setGeometry(QtCore.QRect(500, 1030, 331, 33))
        self.checkBox_ion_3_dist_func.setObjectName("checkBox_ion_3_dist_func")
        self.lineEdit_ion_3_core_temperature = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ion_3_core_temperature.setGeometry(QtCore.QRect(280, 1130, 113, 35))
        self.lineEdit_ion_3_core_temperature.setObjectName("lineEdit_ion_3_core_temperature")
        self.label_ion_3_edge_density = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_3_edge_density.setGeometry(QtCore.QRect(30, 1280, 201, 29))
        self.label_ion_3_edge_density.setObjectName("label_ion_3_edge_density")
        self.label_ion_3_edge_temperature = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_3_edge_temperature.setGeometry(QtCore.QRect(30, 1180, 201, 29))
        self.label_ion_3_edge_temperature.setObjectName("label_ion_3_edge_temperature")
        self.label_ion_3_core_density = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_3_core_density.setGeometry(QtCore.QRect(30, 1230, 201, 29))
        self.label_ion_3_core_density.setObjectName("label_ion_3_core_density")
        self.lineEdit_ion_3_edge_temperature = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ion_3_edge_temperature.setGeometry(QtCore.QRect(280, 1180, 113, 35))
        self.lineEdit_ion_3_edge_temperature.setObjectName("lineEdit_ion_3_edge_temperature")
        self.label_ion_3_core_temperature = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_3_core_temperature.setGeometry(QtCore.QRect(30, 1130, 201, 29))
        self.label_ion_3_core_temperature.setObjectName("label_ion_3_core_temperature")
        self.checkBox_ion_3_disable = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_ion_3_disable.setGeometry(QtCore.QRect(280, 1030, 211, 33))
        self.checkBox_ion_3_disable.setObjectName("checkBox_ion_3_disable")
        self.label_ion_3_keV_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_3_keV_2.setGeometry(QtCore.QRect(400, 1180, 103, 29))
        self.label_ion_3_keV_2.setObjectName("label_ion_3_keV_2")
        self.label_ion_3_species_name = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_3_species_name.setGeometry(QtCore.QRect(30, 1080, 201, 29))
        self.label_ion_3_species_name.setObjectName("label_ion_3_species_name")
        self.label_ion_3_keV_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_3_keV_1.setGeometry(QtCore.QRect(400, 1130, 103, 29))
        self.label_ion_3_keV_1.setObjectName("label_ion_3_keV_1")
        self.lineEdit_ion_3_core_density = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ion_3_core_density.setGeometry(QtCore.QRect(280, 1230, 113, 35))
        self.lineEdit_ion_3_core_density.setObjectName("lineEdit_ion_3_core_density")
        self.label_ion_3_cm3_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_3_cm3_2.setGeometry(QtCore.QRect(400, 1280, 103, 29))
        self.label_ion_3_cm3_2.setObjectName("label_ion_3_cm3_2")
        self.lineEdit_ion_3_edge_density = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ion_3_edge_density.setGeometry(QtCore.QRect(280, 1280, 113, 35))
        self.lineEdit_ion_3_edge_density.setObjectName("lineEdit_ion_3_edge_density")
        self.label_ion_3_cm3_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_3_cm3_1.setGeometry(QtCore.QRect(400, 1230, 103, 29))
        self.label_ion_3_cm3_1.setObjectName("label_ion_3_cm3_1")
        self.label_Ion_Species_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_Ion_Species_3.setGeometry(QtCore.QRect(30, 1030, 161, 29))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_Ion_Species_3.setFont(font)
        self.label_Ion_Species_3.setObjectName("label_Ion_Species_3")
        self.label_Simulation_Parameters = QtWidgets.QLabel(self.centralwidget)
        self.label_Simulation_Parameters.setGeometry(QtCore.QRect(930, 30, 331, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Simulation_Parameters.setFont(font)
        self.label_Simulation_Parameters.setObjectName("label_Simulation_Parameters")
        self.lineEdit_Radial_Bins = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Radial_Bins.setGeometry(QtCore.QRect(1180, 90, 113, 35))
        self.lineEdit_Radial_Bins.setText("")
        self.lineEdit_Radial_Bins.setObjectName("lineEdit_Radial_Bins")
        self.label_Radial_Bins = QtWidgets.QLabel(self.centralwidget)
        self.label_Radial_Bins.setGeometry(QtCore.QRect(930, 90, 201, 29))
        self.label_Radial_Bins.setObjectName("label_Radial_Bins")
        self.pushButton_start_run = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start_run.setGeometry(QtCore.QRect(1600, 1450, 168, 51))
        self.pushButton_start_run.setObjectName("pushButton_start_run")
        self.pushButton_start_run_quit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start_run_quit.setGeometry(QtCore.QRect(1777, 1450, 211, 51))
        self.pushButton_start_run_quit.setObjectName("pushButton_start_run_quit")
        self.pushButton_rf_setup = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_rf_setup.setGeometry(QtCore.QRect(280, 1370, 168, 51))
        self.pushButton_rf_setup.setObjectName("pushButton_rf_setup")
        self.pushButton_nbi_setup = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_nbi_setup.setGeometry(QtCore.QRect(280, 1450, 168, 51))
        self.pushButton_nbi_setup.setObjectName("pushButton_nbi_setup")
        self.pushButton_quit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_quit.setGeometry(QtCore.QRect(2000, 1450, 168, 51))
        self.pushButton_quit.setObjectName("pushButton_quit")
        self.lineEdit_norm_energy = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_norm_energy.setGeometry(QtCore.QRect(1180, 140, 113, 35))
        self.lineEdit_norm_energy.setObjectName("lineEdit_norm_energy")
        self.label_normalization_energy = QtWidgets.QLabel(self.centralwidget)
        self.label_normalization_energy.setGeometry(QtCore.QRect(930, 140, 231, 29))
        self.label_normalization_energy.setObjectName("label_normalization_energy")
        self.label_speed_mesh_points = QtWidgets.QLabel(self.centralwidget)
        self.label_speed_mesh_points.setGeometry(QtCore.QRect(930, 190, 231, 29))
        self.label_speed_mesh_points.setObjectName("label_speed_mesh_points")
        self.lineEdit_speed_mesh_points = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_speed_mesh_points.setGeometry(QtCore.QRect(1180, 190, 113, 35))
        self.lineEdit_speed_mesh_points.setObjectName("lineEdit_speed_mesh_points")
        self.label_theta_mesh_points = QtWidgets.QLabel(self.centralwidget)
        self.label_theta_mesh_points.setGeometry(QtCore.QRect(930, 240, 231, 29))
        self.label_theta_mesh_points.setObjectName("label_theta_mesh_points")
        self.lineEdit_theta_mesh_points = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_theta_mesh_points.setGeometry(QtCore.QRect(1180, 240, 113, 35))
        self.lineEdit_theta_mesh_points.setObjectName("lineEdit_theta_mesh_points")
        self.comboBox_ion_1_species = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_ion_1_species.setGeometry(QtCore.QRect(280, 410, 132, 35))
        self.comboBox_ion_1_species.setObjectName("comboBox_ion_1_species")
        self.comboBox_ion_1_species.addItem("")
        self.comboBox_ion_1_species.addItem("")
        self.comboBox_ion_1_species.addItem("")
        self.comboBox_ion_1_species.addItem("")
        self.comboBox_ion_1_species.addItem("")
        self.comboBox_ion_2_species = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_ion_2_species.setGeometry(QtCore.QRect(280, 740, 132, 35))
        self.comboBox_ion_2_species.setObjectName("comboBox_ion_2_species")
        self.comboBox_ion_2_species.addItem("")
        self.comboBox_ion_2_species.addItem("")
        self.comboBox_ion_2_species.addItem("")
        self.comboBox_ion_2_species.addItem("")
        self.comboBox_ion_2_species.addItem("")
        self.comboBox_ion_3_species = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_ion_3_species.setGeometry(QtCore.QRect(280, 1080, 132, 35))
        self.comboBox_ion_3_species.setObjectName("comboBox_ion_3_species")
        self.comboBox_ion_3_species.addItem("")
        self.comboBox_ion_3_species.addItem("")
        self.comboBox_ion_3_species.addItem("")
        self.comboBox_ion_3_species.addItem("")
        self.comboBox_ion_3_species.addItem("")
        self.label_theta_mesh_points_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_theta_mesh_points_2.setGeometry(QtCore.QRect(930, 290, 231, 29))
        self.label_theta_mesh_points_2.setObjectName("label_theta_mesh_points_2")
        self.lineEdit_theta_mesh_points_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_theta_mesh_points_2.setGeometry(QtCore.QRect(1180, 290, 113, 35))
        self.lineEdit_theta_mesh_points_2.setObjectName("lineEdit_theta_mesh_points_2")
        self.label_theta_mesh_points_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_theta_mesh_points_3.setGeometry(QtCore.QRect(930, 340, 231, 29))
        self.label_theta_mesh_points_3.setObjectName("label_theta_mesh_points_3")
        self.lineEdit_theta_mesh_points_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_theta_mesh_points_3.setGeometry(QtCore.QRect(1180, 340, 113, 35))
        self.lineEdit_theta_mesh_points_3.setObjectName("lineEdit_theta_mesh_points_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkBox_RF.setText(_translate("MainWindow", "&Enable RF"))
        self.checkBox_NBI.setText(_translate("MainWindow", "&Enable NBI"))
        self.label_Basic_Plasma_Parameters.setText(_translate("MainWindow", "Basic Plasma Parameters"))
        self.label_Electrons.setText(_translate("MainWindow", "Electrons"))
        self.label_electron_core_temperature.setText(_translate("MainWindow", "Core Temperature"))
        self.label_electron_edge_temperature.setText(_translate("MainWindow", "Edge Temperature"))
        self.label_electron_keV_1.setText(_translate("MainWindow", "keV"))
        self.label_electron_keV_2.setText(_translate("MainWindow", "keV"))
        self.label_electron_cm3_2.setText(_translate("MainWindow", "cm^-3"))
        self.label_electron_edge_density.setText(_translate("MainWindow", "Edge Density"))
        self.label_electron_core_density.setText(_translate("MainWindow", "Core Density"))
        self.label_electron_cm3_1.setText(_translate("MainWindow", "cm^-3"))
        self.label_ion_1_keV_2.setText(_translate("MainWindow", "keV"))
        self.label_ion_1_cm3_1.setText(_translate("MainWindow", "cm^-3"))
        self.label_Ion_Species_1.setText(_translate("MainWindow", "Ion Species 1"))
        self.label_ion_1_core_density.setText(_translate("MainWindow", "Core Density"))
        self.label_ion_1_edge_temperature.setText(_translate("MainWindow", "Edge Temperature"))
        self.label_ion_1_cm3_2.setText(_translate("MainWindow", "cm^-3"))
        self.label_ion_1_core_temperature.setText(_translate("MainWindow", "Core Temperature"))
        self.label_ion_1_keV_1.setText(_translate("MainWindow", "keV"))
        self.label_ion_1_edge_density.setText(_translate("MainWindow", "Edge Density"))
        self.checkBox_ion_1_dist_func.setText(_translate("MainWindow", "&Track Distribution Function"))
        self.label_ion_1_species_name.setText(_translate("MainWindow", "Species Name"))
        self.checkBox_ion_2_dist_func.setText(_translate("MainWindow", "&Track Distribution Function"))
        self.label_ion_2_species_name.setText(_translate("MainWindow", "Species Name"))
        self.label_ion_2_core_density.setText(_translate("MainWindow", "Core Density"))
        self.label_ion_2_keV_2.setText(_translate("MainWindow", "keV"))
        self.label_ion_2_cm3_1.setText(_translate("MainWindow", "cm^-3"))
        self.label_Ion_Species_2.setText(_translate("MainWindow", "Ion Species 2"))
        self.label_ion_2_edge_density.setText(_translate("MainWindow", "Edge Density"))
        self.label_ion_2_core_temperature.setText(_translate("MainWindow", "Core Temperature"))
        self.label_ion_2_edge_temperature.setText(_translate("MainWindow", "Edge Temperature"))
        self.label_ion_2_cm3_2.setText(_translate("MainWindow", "cm^-3"))
        self.label_ion_2_keV_1.setText(_translate("MainWindow", "keV"))
        self.checkBox_ion_2_disable.setText(_translate("MainWindow", "&Disable Species"))
        self.checkBox_ion_3_dist_func.setText(_translate("MainWindow", "&Track Distribution Function"))
        self.label_ion_3_edge_density.setText(_translate("MainWindow", "Edge Density"))
        self.label_ion_3_edge_temperature.setText(_translate("MainWindow", "Edge Temperature"))
        self.label_ion_3_core_density.setText(_translate("MainWindow", "Core Density"))
        self.label_ion_3_core_temperature.setText(_translate("MainWindow", "Core Temperature"))
        self.checkBox_ion_3_disable.setText(_translate("MainWindow", "&Disable Species"))
        self.label_ion_3_keV_2.setText(_translate("MainWindow", "keV"))
        self.label_ion_3_species_name.setText(_translate("MainWindow", "Species Name"))
        self.label_ion_3_keV_1.setText(_translate("MainWindow", "keV"))
        self.label_ion_3_cm3_2.setText(_translate("MainWindow", "cm^-3"))
        self.label_ion_3_cm3_1.setText(_translate("MainWindow", "cm^-3"))
        self.label_Ion_Species_3.setText(_translate("MainWindow", "Ion Species 3"))
        self.label_Simulation_Parameters.setText(_translate("MainWindow", "Simulation Parameters"))
        self.label_Radial_Bins.setText(_translate("MainWindow", "Radial Bins"))
        self.pushButton_start_run.setText(_translate("MainWindow", "&Start Run"))
        self.pushButton_start_run_quit.setText(_translate("MainWindow", "&Start Run and Quit"))
        self.pushButton_rf_setup.setText(_translate("MainWindow", "&RF Setup"))
        self.pushButton_nbi_setup.setText(_translate("MainWindow", "&NBI Setup"))
        self.pushButton_quit.setText(_translate("MainWindow", "&Quit"))
        self.label_normalization_energy.setText(_translate("MainWindow", "Normalization Energy"))
        self.label_speed_mesh_points.setText(_translate("MainWindow", "Speed Mesh Points"))
        self.label_theta_mesh_points.setText(_translate("MainWindow", "Theta Mesh Points"))
        self.comboBox_ion_1_species.setItemText(0, _translate("MainWindow", "Deuterium"))
        self.comboBox_ion_1_species.setItemText(1, _translate("MainWindow", "Tritium"))
        self.comboBox_ion_1_species.setItemText(2, _translate("MainWindow", "Helium"))
        self.comboBox_ion_1_species.setItemText(3, _translate("MainWindow", "Carbon"))
        self.comboBox_ion_1_species.setItemText(4, _translate("MainWindow", "Tungsten"))
        self.comboBox_ion_2_species.setItemText(0, _translate("MainWindow", "Deuterium"))
        self.comboBox_ion_2_species.setItemText(1, _translate("MainWindow", "Tritium"))
        self.comboBox_ion_2_species.setItemText(2, _translate("MainWindow", "Helium"))
        self.comboBox_ion_2_species.setItemText(3, _translate("MainWindow", "Carbon"))
        self.comboBox_ion_2_species.setItemText(4, _translate("MainWindow", "Tungsten"))
        self.comboBox_ion_3_species.setItemText(0, _translate("MainWindow", "Deuterium"))
        self.comboBox_ion_3_species.setItemText(1, _translate("MainWindow", "Tritium"))
        self.comboBox_ion_3_species.setItemText(2, _translate("MainWindow", "Helium"))
        self.comboBox_ion_3_species.setItemText(3, _translate("MainWindow", "Carbon"))
        self.comboBox_ion_3_species.setItemText(4, _translate("MainWindow", "Tungsten"))
        self.label_theta_mesh_points_2.setText(_translate("MainWindow", "Timestep Size"))
        self.label_theta_mesh_points_3.setText(_translate("MainWindow", "Number of Timesteps"))

