# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CQL3D_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2304, 1588)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.checkBox_RF = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_RF.setGeometry(QtCore.QRect(1850, 90, 145, 33))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_RF.setFont(font)
        self.checkBox_RF.setObjectName("checkBox_RF")
        self.checkBox_NBI = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_NBI.setGeometry(QtCore.QRect(1850, 160, 161, 33))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_NBI.setFont(font)
        self.checkBox_NBI.setObjectName("checkBox_NBI")
        self.label_Basic_Plasma_Parameters = QtWidgets.QLabel(self.centralwidget)
        self.label_Basic_Plasma_Parameters.setGeometry(QtCore.QRect(30, 30, 331, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Basic_Plasma_Parameters.setFont(font)
        self.label_Basic_Plasma_Parameters.setObjectName("label_Basic_Plasma_Parameters")
        self.label_Electrons = QtWidgets.QLabel(self.centralwidget)
        self.label_Electrons.setGeometry(QtCore.QRect(30, 90, 111, 29))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_Electrons.setFont(font)
        self.label_Electrons.setObjectName("label_Electrons")
        self.lineEdit_electron_core_temperature = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_electron_core_temperature.setGeometry(QtCore.QRect(280, 140, 113, 35))
        self.lineEdit_electron_core_temperature.setObjectName("lineEdit_electron_core_temperature")
        self.label_electron_core_temperature = QtWidgets.QLabel(self.centralwidget)
        self.label_electron_core_temperature.setGeometry(QtCore.QRect(30, 140, 201, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_electron_core_temperature.setFont(font)
        self.label_electron_core_temperature.setObjectName("label_electron_core_temperature")
        self.lineEdit_electron_edge_temperature = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_electron_edge_temperature.setGeometry(QtCore.QRect(280, 190, 113, 35))
        self.lineEdit_electron_edge_temperature.setObjectName("lineEdit_electron_edge_temperature")
        self.label_electron_edge_temperature = QtWidgets.QLabel(self.centralwidget)
        self.label_electron_edge_temperature.setGeometry(QtCore.QRect(30, 190, 201, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_electron_edge_temperature.setFont(font)
        self.label_electron_edge_temperature.setObjectName("label_electron_edge_temperature")
        self.label_electron_keV_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_electron_keV_1.setGeometry(QtCore.QRect(400, 140, 103, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_electron_keV_1.setFont(font)
        self.label_electron_keV_1.setObjectName("label_electron_keV_1")
        self.label_electron_keV_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_electron_keV_2.setGeometry(QtCore.QRect(400, 190, 103, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_electron_keV_2.setFont(font)
        self.label_electron_keV_2.setObjectName("label_electron_keV_2")
        self.lineEdit_electron_edge_density = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_electron_edge_density.setGeometry(QtCore.QRect(280, 290, 113, 35))
        self.lineEdit_electron_edge_density.setObjectName("lineEdit_electron_edge_density")
        self.label_electron_cm3_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_electron_cm3_2.setGeometry(QtCore.QRect(400, 290, 103, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_electron_cm3_2.setFont(font)
        self.label_electron_cm3_2.setObjectName("label_electron_cm3_2")
        self.label_electron_edge_density = QtWidgets.QLabel(self.centralwidget)
        self.label_electron_edge_density.setGeometry(QtCore.QRect(30, 290, 201, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_electron_edge_density.setFont(font)
        self.label_electron_edge_density.setObjectName("label_electron_edge_density")
        self.lineEdit_electron_core_density = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_electron_core_density.setGeometry(QtCore.QRect(280, 240, 113, 35))
        self.lineEdit_electron_core_density.setObjectName("lineEdit_electron_core_density")
        self.label_electron_core_density = QtWidgets.QLabel(self.centralwidget)
        self.label_electron_core_density.setGeometry(QtCore.QRect(30, 240, 201, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_electron_core_density.setFont(font)
        self.label_electron_core_density.setObjectName("label_electron_core_density")
        self.label_electron_cm3_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_electron_cm3_1.setGeometry(QtCore.QRect(400, 240, 103, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_electron_cm3_1.setFont(font)
        self.label_electron_cm3_1.setObjectName("label_electron_cm3_1")
        self.lineEdit_ion_1_edge_density = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ion_1_edge_density.setGeometry(QtCore.QRect(280, 600, 113, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_ion_1_edge_density.setFont(font)
        self.lineEdit_ion_1_edge_density.setObjectName("lineEdit_ion_1_edge_density")
        self.lineEdit_ion_1_edge_temperature = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ion_1_edge_temperature.setGeometry(QtCore.QRect(280, 500, 113, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_ion_1_edge_temperature.setFont(font)
        self.lineEdit_ion_1_edge_temperature.setObjectName("lineEdit_ion_1_edge_temperature")
        self.label_ion_1_keV_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_1_keV_2.setGeometry(QtCore.QRect(400, 500, 103, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_ion_1_keV_2.setFont(font)
        self.label_ion_1_keV_2.setObjectName("label_ion_1_keV_2")
        self.label_ion_1_cm3_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_1_cm3_1.setGeometry(QtCore.QRect(400, 550, 103, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_ion_1_cm3_1.setFont(font)
        self.label_ion_1_cm3_1.setObjectName("label_ion_1_cm3_1")
        self.lineEdit_ion_1_core_density = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ion_1_core_density.setGeometry(QtCore.QRect(280, 550, 113, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_ion_1_core_density.setFont(font)
        self.lineEdit_ion_1_core_density.setObjectName("lineEdit_ion_1_core_density")
        self.label_Ion_Species_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_Ion_Species_1.setGeometry(QtCore.QRect(30, 350, 161, 29))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_Ion_Species_1.setFont(font)
        self.label_Ion_Species_1.setObjectName("label_Ion_Species_1")
        self.label_ion_1_core_density = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_1_core_density.setGeometry(QtCore.QRect(30, 550, 201, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_ion_1_core_density.setFont(font)
        self.label_ion_1_core_density.setObjectName("label_ion_1_core_density")
        self.label_ion_1_edge_temperature = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_1_edge_temperature.setGeometry(QtCore.QRect(30, 500, 201, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_ion_1_edge_temperature.setFont(font)
        self.label_ion_1_edge_temperature.setObjectName("label_ion_1_edge_temperature")
        self.label_ion_1_cm3_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_1_cm3_2.setGeometry(QtCore.QRect(400, 600, 103, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_ion_1_cm3_2.setFont(font)
        self.label_ion_1_cm3_2.setObjectName("label_ion_1_cm3_2")
        self.lineEdit_ion_1_core_temperature = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ion_1_core_temperature.setGeometry(QtCore.QRect(280, 450, 113, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_ion_1_core_temperature.setFont(font)
        self.lineEdit_ion_1_core_temperature.setObjectName("lineEdit_ion_1_core_temperature")
        self.label_ion_1_core_temperature = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_1_core_temperature.setGeometry(QtCore.QRect(30, 450, 201, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_ion_1_core_temperature.setFont(font)
        self.label_ion_1_core_temperature.setObjectName("label_ion_1_core_temperature")
        self.label_ion_1_keV_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_1_keV_1.setGeometry(QtCore.QRect(400, 450, 103, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_ion_1_keV_1.setFont(font)
        self.label_ion_1_keV_1.setObjectName("label_ion_1_keV_1")
        self.label_ion_1_edge_density = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_1_edge_density.setGeometry(QtCore.QRect(30, 600, 201, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_ion_1_edge_density.setFont(font)
        self.label_ion_1_edge_density.setObjectName("label_ion_1_edge_density")
        self.checkBox_ion_1_dist_func = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_ion_1_dist_func.setGeometry(QtCore.QRect(280, 350, 331, 33))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_ion_1_dist_func.setFont(font)
        self.checkBox_ion_1_dist_func.setObjectName("checkBox_ion_1_dist_func")
        self.label_ion_1_species_name = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_1_species_name.setGeometry(QtCore.QRect(30, 400, 201, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_ion_1_species_name.setFont(font)
        self.label_ion_1_species_name.setObjectName("label_ion_1_species_name")
        self.lineEdit_ion_2_core_temperature = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ion_2_core_temperature.setGeometry(QtCore.QRect(280, 760, 113, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_ion_2_core_temperature.setFont(font)
        self.lineEdit_ion_2_core_temperature.setObjectName("lineEdit_ion_2_core_temperature")
        self.checkBox_ion_2_dist_func = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_ion_2_dist_func.setGeometry(QtCore.QRect(500, 660, 331, 33))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_ion_2_dist_func.setFont(font)
        self.checkBox_ion_2_dist_func.setObjectName("checkBox_ion_2_dist_func")
        self.lineEdit_ion_2_core_density = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ion_2_core_density.setGeometry(QtCore.QRect(280, 860, 113, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_ion_2_core_density.setFont(font)
        self.lineEdit_ion_2_core_density.setObjectName("lineEdit_ion_2_core_density")
        self.label_ion_2_species_name = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_2_species_name.setGeometry(QtCore.QRect(30, 710, 201, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_ion_2_species_name.setFont(font)
        self.label_ion_2_species_name.setObjectName("label_ion_2_species_name")
        self.label_ion_2_core_density = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_2_core_density.setGeometry(QtCore.QRect(30, 860, 201, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_ion_2_core_density.setFont(font)
        self.label_ion_2_core_density.setObjectName("label_ion_2_core_density")
        self.label_ion_2_keV_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_2_keV_2.setGeometry(QtCore.QRect(400, 810, 103, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_ion_2_keV_2.setFont(font)
        self.label_ion_2_keV_2.setObjectName("label_ion_2_keV_2")
        self.lineEdit_ion_2_edge_density = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ion_2_edge_density.setGeometry(QtCore.QRect(280, 910, 113, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_ion_2_edge_density.setFont(font)
        self.lineEdit_ion_2_edge_density.setObjectName("lineEdit_ion_2_edge_density")
        self.label_ion_2_cm3_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_2_cm3_1.setGeometry(QtCore.QRect(400, 860, 103, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_ion_2_cm3_1.setFont(font)
        self.label_ion_2_cm3_1.setObjectName("label_ion_2_cm3_1")
        self.label_Ion_Species_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_Ion_Species_2.setGeometry(QtCore.QRect(30, 660, 161, 29))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_Ion_Species_2.setFont(font)
        self.label_Ion_Species_2.setObjectName("label_Ion_Species_2")
        self.lineEdit_ion_2_edge_temperature = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ion_2_edge_temperature.setGeometry(QtCore.QRect(280, 810, 113, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_ion_2_edge_temperature.setFont(font)
        self.lineEdit_ion_2_edge_temperature.setObjectName("lineEdit_ion_2_edge_temperature")
        self.label_ion_2_edge_density = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_2_edge_density.setGeometry(QtCore.QRect(30, 910, 201, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_ion_2_edge_density.setFont(font)
        self.label_ion_2_edge_density.setObjectName("label_ion_2_edge_density")
        self.label_ion_2_core_temperature = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_2_core_temperature.setGeometry(QtCore.QRect(30, 760, 201, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_ion_2_core_temperature.setFont(font)
        self.label_ion_2_core_temperature.setObjectName("label_ion_2_core_temperature")
        self.label_ion_2_edge_temperature = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_2_edge_temperature.setGeometry(QtCore.QRect(30, 810, 201, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_ion_2_edge_temperature.setFont(font)
        self.label_ion_2_edge_temperature.setObjectName("label_ion_2_edge_temperature")
        self.label_ion_2_cm3_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_2_cm3_2.setGeometry(QtCore.QRect(400, 910, 103, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_ion_2_cm3_2.setFont(font)
        self.label_ion_2_cm3_2.setObjectName("label_ion_2_cm3_2")
        self.label_ion_2_keV_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_2_keV_1.setGeometry(QtCore.QRect(400, 760, 103, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_ion_2_keV_1.setFont(font)
        self.label_ion_2_keV_1.setObjectName("label_ion_2_keV_1")
        self.checkBox_ion_2_enable = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_ion_2_enable.setGeometry(QtCore.QRect(280, 660, 211, 33))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_ion_2_enable.setFont(font)
        self.checkBox_ion_2_enable.setObjectName("checkBox_ion_2_enable")
        self.checkBox_ion_3_dist_func = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_ion_3_dist_func.setGeometry(QtCore.QRect(500, 980, 331, 33))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_ion_3_dist_func.setFont(font)
        self.checkBox_ion_3_dist_func.setObjectName("checkBox_ion_3_dist_func")
        self.lineEdit_ion_3_core_temperature = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ion_3_core_temperature.setGeometry(QtCore.QRect(280, 1080, 113, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_ion_3_core_temperature.setFont(font)
        self.lineEdit_ion_3_core_temperature.setObjectName("lineEdit_ion_3_core_temperature")
        self.label_ion_3_edge_density = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_3_edge_density.setGeometry(QtCore.QRect(30, 1230, 201, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_ion_3_edge_density.setFont(font)
        self.label_ion_3_edge_density.setObjectName("label_ion_3_edge_density")
        self.label_ion_3_edge_temperature = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_3_edge_temperature.setGeometry(QtCore.QRect(30, 1130, 201, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_ion_3_edge_temperature.setFont(font)
        self.label_ion_3_edge_temperature.setObjectName("label_ion_3_edge_temperature")
        self.label_ion_3_core_density = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_3_core_density.setGeometry(QtCore.QRect(30, 1180, 201, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_ion_3_core_density.setFont(font)
        self.label_ion_3_core_density.setObjectName("label_ion_3_core_density")
        self.lineEdit_ion_3_edge_temperature = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ion_3_edge_temperature.setGeometry(QtCore.QRect(280, 1130, 113, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_ion_3_edge_temperature.setFont(font)
        self.lineEdit_ion_3_edge_temperature.setObjectName("lineEdit_ion_3_edge_temperature")
        self.label_ion_3_core_temperature = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_3_core_temperature.setGeometry(QtCore.QRect(30, 1080, 201, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_ion_3_core_temperature.setFont(font)
        self.label_ion_3_core_temperature.setObjectName("label_ion_3_core_temperature")
        self.checkBox_ion_3_enable = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_ion_3_enable.setGeometry(QtCore.QRect(280, 980, 211, 33))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_ion_3_enable.setFont(font)
        self.checkBox_ion_3_enable.setObjectName("checkBox_ion_3_enable")
        self.label_ion_3_keV_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_3_keV_2.setGeometry(QtCore.QRect(400, 1130, 103, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_ion_3_keV_2.setFont(font)
        self.label_ion_3_keV_2.setObjectName("label_ion_3_keV_2")
        self.label_ion_3_species_name = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_3_species_name.setGeometry(QtCore.QRect(30, 1030, 201, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_ion_3_species_name.setFont(font)
        self.label_ion_3_species_name.setObjectName("label_ion_3_species_name")
        self.label_ion_3_keV_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_3_keV_1.setGeometry(QtCore.QRect(400, 1080, 103, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_ion_3_keV_1.setFont(font)
        self.label_ion_3_keV_1.setObjectName("label_ion_3_keV_1")
        self.lineEdit_ion_3_core_density = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ion_3_core_density.setGeometry(QtCore.QRect(280, 1180, 113, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_ion_3_core_density.setFont(font)
        self.lineEdit_ion_3_core_density.setObjectName("lineEdit_ion_3_core_density")
        self.label_ion_3_cm3_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_3_cm3_2.setGeometry(QtCore.QRect(400, 1230, 103, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_ion_3_cm3_2.setFont(font)
        self.label_ion_3_cm3_2.setObjectName("label_ion_3_cm3_2")
        self.lineEdit_ion_3_edge_density = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ion_3_edge_density.setGeometry(QtCore.QRect(280, 1230, 113, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_ion_3_edge_density.setFont(font)
        self.lineEdit_ion_3_edge_density.setObjectName("lineEdit_ion_3_edge_density")
        self.label_ion_3_cm3_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_ion_3_cm3_1.setGeometry(QtCore.QRect(400, 1180, 103, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_ion_3_cm3_1.setFont(font)
        self.label_ion_3_cm3_1.setObjectName("label_ion_3_cm3_1")
        self.label_Ion_Species_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_Ion_Species_3.setGeometry(QtCore.QRect(30, 980, 161, 29))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_Ion_Species_3.setFont(font)
        self.label_Ion_Species_3.setObjectName("label_Ion_Species_3")
        self.label_Simulation_Parameters = QtWidgets.QLabel(self.centralwidget)
        self.label_Simulation_Parameters.setGeometry(QtCore.QRect(930, 30, 331, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Simulation_Parameters.setFont(font)
        self.label_Simulation_Parameters.setObjectName("label_Simulation_Parameters")
        self.lineEdit_Radial_Bins = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Radial_Bins.setGeometry(QtCore.QRect(1180, 190, 113, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_Radial_Bins.setFont(font)
        self.lineEdit_Radial_Bins.setObjectName("lineEdit_Radial_Bins")
        self.label_Radial_Bins = QtWidgets.QLabel(self.centralwidget)
        self.label_Radial_Bins.setGeometry(QtCore.QRect(930, 190, 201, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_Radial_Bins.setFont(font)
        self.label_Radial_Bins.setObjectName("label_Radial_Bins")
        self.pushButton_start_run = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start_run.setGeometry(QtCore.QRect(1600, 1450, 168, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_start_run.setFont(font)
        self.pushButton_start_run.setObjectName("pushButton_start_run")
        self.pushButton_start_run_quit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start_run_quit.setGeometry(QtCore.QRect(1777, 1450, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_start_run_quit.setFont(font)
        self.pushButton_start_run_quit.setObjectName("pushButton_start_run_quit")
        self.pushButton_rf_setup = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_rf_setup.setGeometry(QtCore.QRect(2020, 80, 168, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_rf_setup.setFont(font)
        self.pushButton_rf_setup.setObjectName("pushButton_rf_setup")
        self.pushButton_nbi_setup = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_nbi_setup.setGeometry(QtCore.QRect(2020, 150, 168, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_nbi_setup.setFont(font)
        self.pushButton_nbi_setup.setObjectName("pushButton_nbi_setup")
        self.pushButton_quit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_quit.setGeometry(QtCore.QRect(2000, 1450, 168, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_quit.setFont(font)
        self.pushButton_quit.setObjectName("pushButton_quit")
        self.label_speed_mesh_points = QtWidgets.QLabel(self.centralwidget)
        self.label_speed_mesh_points.setGeometry(QtCore.QRect(930, 240, 231, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_speed_mesh_points.setFont(font)
        self.label_speed_mesh_points.setObjectName("label_speed_mesh_points")
        self.lineEdit_speed_mesh_points = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_speed_mesh_points.setGeometry(QtCore.QRect(1180, 240, 113, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_speed_mesh_points.setFont(font)
        self.lineEdit_speed_mesh_points.setObjectName("lineEdit_speed_mesh_points")
        self.label_theta_mesh_points = QtWidgets.QLabel(self.centralwidget)
        self.label_theta_mesh_points.setGeometry(QtCore.QRect(930, 290, 231, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_theta_mesh_points.setFont(font)
        self.label_theta_mesh_points.setObjectName("label_theta_mesh_points")
        self.lineEdit_theta_mesh_points = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_theta_mesh_points.setGeometry(QtCore.QRect(1180, 290, 113, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_theta_mesh_points.setFont(font)
        self.lineEdit_theta_mesh_points.setObjectName("lineEdit_theta_mesh_points")
        self.comboBox_ion_1_species = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_ion_1_species.setGeometry(QtCore.QRect(280, 400, 132, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBox_ion_1_species.setFont(font)
        self.comboBox_ion_1_species.setObjectName("comboBox_ion_1_species")
        self.comboBox_ion_1_species.addItem("")
        self.comboBox_ion_1_species.addItem("")
        self.comboBox_ion_1_species.addItem("")
        self.comboBox_ion_1_species.addItem("")
        self.comboBox_ion_1_species.addItem("")
        self.comboBox_ion_1_species.addItem("")
        self.comboBox_ion_2_species = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_ion_2_species.setGeometry(QtCore.QRect(280, 710, 132, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBox_ion_2_species.setFont(font)
        self.comboBox_ion_2_species.setObjectName("comboBox_ion_2_species")
        self.comboBox_ion_2_species.addItem("")
        self.comboBox_ion_2_species.addItem("")
        self.comboBox_ion_2_species.addItem("")
        self.comboBox_ion_2_species.addItem("")
        self.comboBox_ion_2_species.addItem("")
        self.comboBox_ion_2_species.addItem("")
        self.comboBox_ion_3_species = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_ion_3_species.setGeometry(QtCore.QRect(280, 1030, 132, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBox_ion_3_species.setFont(font)
        self.comboBox_ion_3_species.setObjectName("comboBox_ion_3_species")
        self.comboBox_ion_3_species.addItem("")
        self.comboBox_ion_3_species.addItem("")
        self.comboBox_ion_3_species.addItem("")
        self.comboBox_ion_3_species.addItem("")
        self.comboBox_ion_3_species.addItem("")
        self.comboBox_ion_3_species.addItem("")
        self.label_timestep_size = QtWidgets.QLabel(self.centralwidget)
        self.label_timestep_size.setGeometry(QtCore.QRect(930, 340, 231, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_timestep_size.setFont(font)
        self.label_timestep_size.setObjectName("label_timestep_size")
        self.lineEdit_timestep_size = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_timestep_size.setGeometry(QtCore.QRect(1180, 340, 113, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_timestep_size.setFont(font)
        self.lineEdit_timestep_size.setObjectName("lineEdit_timestep_size")
        self.label_timestep_number = QtWidgets.QLabel(self.centralwidget)
        self.label_timestep_number.setGeometry(QtCore.QRect(930, 390, 231, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_timestep_number.setFont(font)
        self.label_timestep_number.setObjectName("label_timestep_number")
        self.lineEdit_timestep_number = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_timestep_number.setGeometry(QtCore.QRect(1180, 390, 113, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_timestep_number.setFont(font)
        self.lineEdit_timestep_number.setObjectName("lineEdit_timestep_number")
        self.label_eqdsk = QtWidgets.QLabel(self.centralwidget)
        self.label_eqdsk.setGeometry(QtCore.QRect(930, 640, 171, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_eqdsk.setFont(font)
        self.label_eqdsk.setObjectName("label_eqdsk")
        self.label_eqdsk_filepath = QtWidgets.QLabel(self.centralwidget)
        self.label_eqdsk_filepath.setGeometry(QtCore.QRect(930, 700, 201, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_eqdsk_filepath.setFont(font)
        self.label_eqdsk_filepath.setObjectName("label_eqdsk_filepath")
        self.lineEdit_eqdsk_filepath = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_eqdsk_filepath.setGeometry(QtCore.QRect(1180, 700, 500, 35))
        self.lineEdit_eqdsk_filepath.setText("")
        self.lineEdit_eqdsk_filepath.setObjectName("lineEdit_eqdsk_filepath")
        self.label_input_mnemonic = QtWidgets.QLabel(self.centralwidget)
        self.label_input_mnemonic.setGeometry(QtCore.QRect(930, 90, 201, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_input_mnemonic.setFont(font)
        self.label_input_mnemonic.setObjectName("label_input_mnemonic")
        self.lineEdit_input_mnemonic = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_input_mnemonic.setGeometry(QtCore.QRect(1180, 90, 500, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_input_mnemonic.setFont(font)
        self.lineEdit_input_mnemonic.setText("")
        self.lineEdit_input_mnemonic.setObjectName("lineEdit_input_mnemonic")
        self.label_timestep_size_unit = QtWidgets.QLabel(self.centralwidget)
        self.label_timestep_size_unit.setGeometry(QtCore.QRect(1300, 340, 103, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_timestep_size_unit.setFont(font)
        self.label_timestep_size_unit.setObjectName("label_timestep_size_unit")
        self.label_output_mnemonic = QtWidgets.QLabel(self.centralwidget)
        self.label_output_mnemonic.setGeometry(QtCore.QRect(930, 140, 201, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_output_mnemonic.setFont(font)
        self.label_output_mnemonic.setObjectName("label_output_mnemonic")
        self.lineEdit_output_mnemonic = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_output_mnemonic.setGeometry(QtCore.QRect(1180, 140, 500, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_output_mnemonic.setFont(font)
        self.lineEdit_output_mnemonic.setText("")
        self.lineEdit_output_mnemonic.setObjectName("lineEdit_output_mnemonic")
        self.label_fusion_diagnostics = QtWidgets.QLabel(self.centralwidget)
        self.label_fusion_diagnostics.setGeometry(QtCore.QRect(930, 750, 251, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_fusion_diagnostics.setFont(font)
        self.label_fusion_diagnostics.setObjectName("label_fusion_diagnostics")
        self.label_radial_pos = QtWidgets.QLabel(self.centralwidget)
        self.label_radial_pos.setGeometry(QtCore.QRect(930, 810, 231, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_radial_pos.setFont(font)
        self.label_radial_pos.setObjectName("label_radial_pos")
        self.lineEdit_rad_pos = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_rad_pos.setGeometry(QtCore.QRect(1180, 810, 113, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_rad_pos.setFont(font)
        self.lineEdit_rad_pos.setObjectName("lineEdit_rad_pos")
        self.label_axial_pos = QtWidgets.QLabel(self.centralwidget)
        self.label_axial_pos.setGeometry(QtCore.QRect(930, 860, 231, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_axial_pos.setFont(font)
        self.label_axial_pos.setObjectName("label_axial_pos")
        self.lineEdit_ax_pos = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ax_pos.setGeometry(QtCore.QRect(1180, 860, 113, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_ax_pos.setFont(font)
        self.lineEdit_ax_pos.setObjectName("lineEdit_ax_pos")
        self.label_radial_position_unit = QtWidgets.QLabel(self.centralwidget)
        self.label_radial_position_unit.setGeometry(QtCore.QRect(1300, 810, 103, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_radial_position_unit.setFont(font)
        self.label_radial_position_unit.setObjectName("label_radial_position_unit")
        self.label_axial_position_unit = QtWidgets.QLabel(self.centralwidget)
        self.label_axial_position_unit.setGeometry(QtCore.QRect(1300, 860, 103, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_axial_position_unit.setFont(font)
        self.label_axial_position_unit.setObjectName("label_axial_position_unit")
        self.lineEdit_thet1_fus = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_thet1_fus.setGeometry(QtCore.QRect(1180, 910, 113, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_thet1_fus.setFont(font)
        self.lineEdit_thet1_fus.setObjectName("lineEdit_thet1_fus")
        self.label_theta_1_unit = QtWidgets.QLabel(self.centralwidget)
        self.label_theta_1_unit.setGeometry(QtCore.QRect(1300, 910, 103, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_theta_1_unit.setFont(font)
        self.label_theta_1_unit.setObjectName("label_theta_1_unit")
        self.label_thet1_fus = QtWidgets.QLabel(self.centralwidget)
        self.label_thet1_fus.setGeometry(QtCore.QRect(930, 910, 231, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_thet1_fus.setFont(font)
        self.label_thet1_fus.setObjectName("label_thet1_fus")
        self.lineEdit_thet2_fus = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_thet2_fus.setGeometry(QtCore.QRect(1180, 960, 113, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_thet2_fus.setFont(font)
        self.lineEdit_thet2_fus.setObjectName("lineEdit_thet2_fus")
        self.label_theta_2_unit = QtWidgets.QLabel(self.centralwidget)
        self.label_theta_2_unit.setGeometry(QtCore.QRect(1300, 960, 103, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_theta_2_unit.setFont(font)
        self.label_theta_2_unit.setObjectName("label_theta_2_unit")
        self.label_thet2_fus = QtWidgets.QLabel(self.centralwidget)
        self.label_thet2_fus.setGeometry(QtCore.QRect(930, 960, 231, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_thet2_fus.setFont(font)
        self.label_thet2_fus.setObjectName("label_thet2_fus")
        self.lineEdit_fds_fus = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_fds_fus.setGeometry(QtCore.QRect(1180, 1010, 113, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_fds_fus.setFont(font)
        self.lineEdit_fds_fus.setObjectName("lineEdit_fds_fus")
        self.label_fds_fus = QtWidgets.QLabel(self.centralwidget)
        self.label_fds_fus.setGeometry(QtCore.QRect(930, 1010, 231, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_fds_fus.setFont(font)
        self.label_fds_fus.setObjectName("label_fds_fus")
        self.lineEdit_max_spectra = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_max_spectra.setGeometry(QtCore.QRect(1180, 490, 113, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_max_spectra.setFont(font)
        self.lineEdit_max_spectra.setObjectName("lineEdit_max_spectra")
        self.label_max_spectra = QtWidgets.QLabel(self.centralwidget)
        self.label_max_spectra.setGeometry(QtCore.QRect(930, 490, 251, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_max_spectra.setFont(font)
        self.label_max_spectra.setObjectName("label_max_spectra")
        self.lineEdit_min_spectra = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_min_spectra.setGeometry(QtCore.QRect(1180, 540, 113, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_min_spectra.setFont(font)
        self.lineEdit_min_spectra.setObjectName("lineEdit_min_spectra")
        self.label_min_spectra = QtWidgets.QLabel(self.centralwidget)
        self.label_min_spectra.setGeometry(QtCore.QRect(930, 540, 251, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_min_spectra.setFont(font)
        self.label_min_spectra.setObjectName("label_min_spectra")
        self.label_enmax_unit = QtWidgets.QLabel(self.centralwidget)
        self.label_enmax_unit.setGeometry(QtCore.QRect(1300, 490, 103, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_enmax_unit.setFont(font)
        self.label_enmax_unit.setObjectName("label_enmax_unit")
        self.label_enmin_unit = QtWidgets.QLabel(self.centralwidget)
        self.label_enmin_unit.setGeometry(QtCore.QRect(1300, 540, 103, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_enmin_unit.setFont(font)
        self.label_enmin_unit.setObjectName("label_enmin_unit")
        self.label_normalization_energy = QtWidgets.QLabel(self.centralwidget)
        self.label_normalization_energy.setGeometry(QtCore.QRect(930, 440, 231, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_normalization_energy.setFont(font)
        self.label_normalization_energy.setObjectName("label_normalization_energy")
        self.label_enorm_unit = QtWidgets.QLabel(self.centralwidget)
        self.label_enorm_unit.setGeometry(QtCore.QRect(1300, 440, 103, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_enorm_unit.setFont(font)
        self.label_enorm_unit.setObjectName("label_enorm_unit")
        self.lineEdit_norm_energy = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_norm_energy.setGeometry(QtCore.QRect(1180, 440, 113, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_norm_energy.setFont(font)
        self.lineEdit_norm_energy.setObjectName("lineEdit_norm_energy")
        self.label_throat_pot_jump = QtWidgets.QLabel(self.centralwidget)
        self.label_throat_pot_jump.setGeometry(QtCore.QRect(930, 590, 251, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_throat_pot_jump.setFont(font)
        self.label_throat_pot_jump.setObjectName("label_throat_pot_jump")
        self.lineEdit_ephicc = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ephicc.setGeometry(QtCore.QRect(1180, 590, 113, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_ephicc.setFont(font)
        self.lineEdit_ephicc.setObjectName("lineEdit_ephicc")
        self.label_ephicc_unit = QtWidgets.QLabel(self.centralwidget)
        self.label_ephicc_unit.setGeometry(QtCore.QRect(1300, 590, 103, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_ephicc_unit.setFont(font)
        self.label_ephicc_unit.setObjectName("label_ephicc_unit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1210, 1450, 177, 54))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_read_old_cqlinput = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_read_old_cqlinput.setGeometry(QtCore.QRect(680, 1460, 500, 35))
        self.lineEdit_read_old_cqlinput.setText("")
        self.lineEdit_read_old_cqlinput.setObjectName("lineEdit_read_old_cqlinput")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CQL3D GUI"))
        self.checkBox_RF.setText(_translate("MainWindow", "&Enable RF"))
        self.checkBox_NBI.setText(_translate("MainWindow", "&Enable NBI"))
        self.label_Basic_Plasma_Parameters.setText(_translate("MainWindow", "Basic Plasma Parameters"))
        self.label_Electrons.setText(_translate("MainWindow", "Electrons"))
        self.label_electron_core_temperature.setText(_translate("MainWindow", "Core Temperature"))
        self.label_electron_edge_temperature.setText(_translate("MainWindow", "Edge Temperature"))
        self.label_electron_keV_1.setText(_translate("MainWindow", "keV"))
        self.label_electron_keV_2.setText(_translate("MainWindow", "keV"))
        self.label_electron_cm3_2.setText(_translate("MainWindow", "cm^-3"))
        self.label_electron_edge_density.setText(_translate("MainWindow", "Edge Density"))
        self.label_electron_core_density.setText(_translate("MainWindow", "Core Density"))
        self.label_electron_cm3_1.setText(_translate("MainWindow", "cm^-3"))
        self.label_ion_1_keV_2.setText(_translate("MainWindow", "keV"))
        self.label_ion_1_cm3_1.setText(_translate("MainWindow", "cm^-3"))
        self.label_Ion_Species_1.setText(_translate("MainWindow", "Ion Species 1"))
        self.label_ion_1_core_density.setText(_translate("MainWindow", "Core Density"))
        self.label_ion_1_edge_temperature.setText(_translate("MainWindow", "Edge Temperature"))
        self.label_ion_1_cm3_2.setText(_translate("MainWindow", "cm^-3"))
        self.label_ion_1_core_temperature.setText(_translate("MainWindow", "Core Temperature"))
        self.label_ion_1_keV_1.setText(_translate("MainWindow", "keV"))
        self.label_ion_1_edge_density.setText(_translate("MainWindow", "Edge Density"))
        self.checkBox_ion_1_dist_func.setText(_translate("MainWindow", "&Track Distribution Function"))
        self.label_ion_1_species_name.setText(_translate("MainWindow", "Species Name"))
        self.checkBox_ion_2_dist_func.setText(_translate("MainWindow", "&Track Distribution Function"))
        self.label_ion_2_species_name.setText(_translate("MainWindow", "Species Name"))
        self.label_ion_2_core_density.setText(_translate("MainWindow", "Core Density"))
        self.label_ion_2_keV_2.setText(_translate("MainWindow", "keV"))
        self.label_ion_2_cm3_1.setText(_translate("MainWindow", "cm^-3"))
        self.label_Ion_Species_2.setText(_translate("MainWindow", "Ion Species 2"))
        self.label_ion_2_edge_density.setText(_translate("MainWindow", "Edge Density"))
        self.label_ion_2_core_temperature.setText(_translate("MainWindow", "Core Temperature"))
        self.label_ion_2_edge_temperature.setText(_translate("MainWindow", "Edge Temperature"))
        self.label_ion_2_cm3_2.setText(_translate("MainWindow", "cm^-3"))
        self.label_ion_2_keV_1.setText(_translate("MainWindow", "keV"))
        self.checkBox_ion_2_enable.setText(_translate("MainWindow", "&Enable Species"))
        self.checkBox_ion_3_dist_func.setText(_translate("MainWindow", "&Track Distribution Function"))
        self.label_ion_3_edge_density.setText(_translate("MainWindow", "Edge Density"))
        self.label_ion_3_edge_temperature.setText(_translate("MainWindow", "Edge Temperature"))
        self.label_ion_3_core_density.setText(_translate("MainWindow", "Core Density"))
        self.label_ion_3_core_temperature.setText(_translate("MainWindow", "Core Temperature"))
        self.checkBox_ion_3_enable.setText(_translate("MainWindow", "&Enable Species"))
        self.label_ion_3_keV_2.setText(_translate("MainWindow", "keV"))
        self.label_ion_3_species_name.setText(_translate("MainWindow", "Species Name"))
        self.label_ion_3_keV_1.setText(_translate("MainWindow", "keV"))
        self.label_ion_3_cm3_2.setText(_translate("MainWindow", "cm^-3"))
        self.label_ion_3_cm3_1.setText(_translate("MainWindow", "cm^-3"))
        self.label_Ion_Species_3.setText(_translate("MainWindow", "Ion Species 3"))
        self.label_Simulation_Parameters.setText(_translate("MainWindow", "Simulation Parameters"))
        self.lineEdit_Radial_Bins.setText(_translate("MainWindow", "10"))
        self.label_Radial_Bins.setText(_translate("MainWindow", "Radial Bins"))
        self.pushButton_start_run.setText(_translate("MainWindow", "&Start Run"))
        self.pushButton_start_run_quit.setText(_translate("MainWindow", "&Start Run and Quit"))
        self.pushButton_rf_setup.setText(_translate("MainWindow", "&RF Setup"))
        self.pushButton_nbi_setup.setText(_translate("MainWindow", "&NBI Setup"))
        self.pushButton_quit.setText(_translate("MainWindow", "&Quit"))
        self.label_speed_mesh_points.setText(_translate("MainWindow", "Speed Mesh Points"))
        self.label_theta_mesh_points.setText(_translate("MainWindow", "Theta Mesh Points"))
        self.comboBox_ion_1_species.setItemText(0, _translate("MainWindow", "Deuterium"))
        self.comboBox_ion_1_species.setItemText(1, _translate("MainWindow", "Tritium"))
        self.comboBox_ion_1_species.setItemText(2, _translate("MainWindow", "Helium-3"))
        self.comboBox_ion_1_species.setItemText(3, _translate("MainWindow", "Helium-4"))
        self.comboBox_ion_1_species.setItemText(4, _translate("MainWindow", "Carbon"))
        self.comboBox_ion_1_species.setItemText(5, _translate("MainWindow", "Tungsten"))
        self.comboBox_ion_2_species.setItemText(0, _translate("MainWindow", "Deuterium"))
        self.comboBox_ion_2_species.setItemText(1, _translate("MainWindow", "Tritium"))
        self.comboBox_ion_2_species.setItemText(2, _translate("MainWindow", "Helium-3"))
        self.comboBox_ion_2_species.setItemText(3, _translate("MainWindow", "Helium-4"))
        self.comboBox_ion_2_species.setItemText(4, _translate("MainWindow", "Carbon"))
        self.comboBox_ion_2_species.setItemText(5, _translate("MainWindow", "Tungsten"))
        self.comboBox_ion_3_species.setItemText(0, _translate("MainWindow", "Deuterium"))
        self.comboBox_ion_3_species.setItemText(1, _translate("MainWindow", "Tritium"))
        self.comboBox_ion_3_species.setItemText(2, _translate("MainWindow", "Helium-3"))
        self.comboBox_ion_3_species.setItemText(3, _translate("MainWindow", "Helium-4"))
        self.comboBox_ion_3_species.setItemText(4, _translate("MainWindow", "Carbon"))
        self.comboBox_ion_3_species.setItemText(5, _translate("MainWindow", "Tungsten"))
        self.label_timestep_size.setText(_translate("MainWindow", "Timestep Size"))
        self.lineEdit_timestep_size.setText(_translate("MainWindow", "0.001"))
        self.label_timestep_number.setText(_translate("MainWindow", "Number of Timesteps"))
        self.label_eqdsk.setText(_translate("MainWindow", "eqdsk Setup"))
        self.label_eqdsk_filepath.setText(_translate("MainWindow", "Filepath"))
        self.label_input_mnemonic.setText(_translate("MainWindow", "cqlinput Mnemonic"))
        self.label_timestep_size_unit.setText(_translate("MainWindow", "s"))
        self.label_output_mnemonic.setText(_translate("MainWindow", "Output Mnemonic"))
        self.label_fusion_diagnostics.setText(_translate("MainWindow", "Fusion Diagnostics"))
        self.label_radial_pos.setText(_translate("MainWindow", "Radial Positions"))
        self.label_axial_pos.setText(_translate("MainWindow", "Axial Positions"))
        self.label_radial_position_unit.setText(_translate("MainWindow", "cm"))
        self.label_axial_position_unit.setText(_translate("MainWindow", "cm"))
        self.lineEdit_thet1_fus.setText(_translate("MainWindow", "np.full(70,90)"))
        self.label_theta_1_unit.setText(_translate("MainWindow", "deg"))
        self.label_thet1_fus.setText(_translate("MainWindow", "Polar Angle"))
        self.lineEdit_thet2_fus.setText(_translate("MainWindow", "np.full(70,180)"))
        self.label_theta_2_unit.setText(_translate("MainWindow", "deg"))
        self.label_thet2_fus.setText(_translate("MainWindow", "Toroidal Angle"))
        self.lineEdit_fds_fus.setText(_translate("MainWindow", "0.5"))
        self.label_fds_fus.setText(_translate("MainWindow", "Step Size"))
        self.label_max_spectra.setText(_translate("MainWindow", "Max Energy of Spectra"))
        self.label_min_spectra.setText(_translate("MainWindow", "Min Energy of Spectra"))
        self.label_enmax_unit.setText(_translate("MainWindow", "keV"))
        self.label_enmin_unit.setText(_translate("MainWindow", "keV"))
        self.label_normalization_energy.setText(_translate("MainWindow", "Normalization Energy"))
        self.label_enorm_unit.setText(_translate("MainWindow", "keV"))
        self.label_throat_pot_jump.setText(_translate("MainWindow", "Throat Potential Jump"))
        self.label_ephicc_unit.setText(_translate("MainWindow", "keV"))
        self.pushButton.setText(_translate("MainWindow", "Read cqlinput"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

