# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RF_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2614, 1103)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_genray_filepath = QtWidgets.QLabel(self.centralwidget)
        self.label_genray_filepath.setGeometry(QtCore.QRect(30, 90, 201, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_genray_filepath.setFont(font)
        self.label_genray_filepath.setObjectName("label_genray_filepath")
        self.lineEdit_eqdsk_filepath = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_eqdsk_filepath.setGeometry(QtCore.QRect(280, 90, 500, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_eqdsk_filepath.setFont(font)
        self.lineEdit_eqdsk_filepath.setText("")
        self.lineEdit_eqdsk_filepath.setObjectName("lineEdit_eqdsk_filepath")
        self.label_powerscale = QtWidgets.QLabel(self.centralwidget)
        self.label_powerscale.setGeometry(QtCore.QRect(30, 140, 201, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_powerscale.setFont(font)
        self.label_powerscale.setObjectName("label_powerscale")
        self.lineEdit_powerscale = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_powerscale.setGeometry(QtCore.QRect(280, 140, 113, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_powerscale.setFont(font)
        self.lineEdit_powerscale.setText("")
        self.lineEdit_powerscale.setObjectName("lineEdit_powerscale")
        self.label_1st_harm = QtWidgets.QLabel(self.centralwidget)
        self.label_1st_harm.setGeometry(QtCore.QRect(30, 190, 251, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_1st_harm.setFont(font)
        self.label_1st_harm.setObjectName("label_1st_harm")
        self.lineEdit_1st_harm = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_1st_harm.setGeometry(QtCore.QRect(280, 190, 113, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_1st_harm.setFont(font)
        self.lineEdit_1st_harm.setText("")
        self.lineEdit_1st_harm.setObjectName("lineEdit_1st_harm")
        self.label_num_harms = QtWidgets.QLabel(self.centralwidget)
        self.label_num_harms.setGeometry(QtCore.QRect(30, 240, 241, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_num_harms.setFont(font)
        self.label_num_harms.setObjectName("label_num_harms")
        self.lineEdit_num_harms = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_num_harms.setGeometry(QtCore.QRect(280, 240, 113, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_num_harms.setFont(font)
        self.lineEdit_num_harms.setText("")
        self.lineEdit_num_harms.setObjectName("lineEdit_num_harms")
        self.label_Ion_Species_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_Ion_Species_1.setGeometry(QtCore.QRect(30, 30, 181, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Ion_Species_1.setFont(font)
        self.label_Ion_Species_1.setObjectName("label_Ion_Species_1")
        self.pushButton_quit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_quit.setGeometry(QtCore.QRect(2390, 970, 168, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_quit.setFont(font)
        self.pushButton_quit.setObjectName("pushButton_quit")
        self.pushButton_save_data_quit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_save_data_quit.setGeometry(QtCore.QRect(2157, 970, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_save_data_quit.setFont(font)
        self.pushButton_save_data_quit.setObjectName("pushButton_save_data_quit")
        self.pushButton_save_data = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_save_data.setGeometry(QtCore.QRect(1980, 970, 168, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_save_data.setFont(font)
        self.pushButton_save_data.setObjectName("pushButton_save_data")
        self.lineEdit_eqdsk_filepath_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_eqdsk_filepath_2.setGeometry(QtCore.QRect(1070, 90, 500, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_eqdsk_filepath_2.setFont(font)
        self.lineEdit_eqdsk_filepath_2.setText("")
        self.lineEdit_eqdsk_filepath_2.setObjectName("lineEdit_eqdsk_filepath_2")
        self.label_powerscale_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_powerscale_2.setGeometry(QtCore.QRect(820, 140, 201, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_powerscale_2.setFont(font)
        self.label_powerscale_2.setObjectName("label_powerscale_2")
        self.label_1st_harm_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_1st_harm_2.setGeometry(QtCore.QRect(820, 190, 251, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_1st_harm_2.setFont(font)
        self.label_1st_harm_2.setObjectName("label_1st_harm_2")
        self.lineEdit_1st_harm_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_1st_harm_2.setGeometry(QtCore.QRect(1070, 190, 113, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_1st_harm_2.setFont(font)
        self.lineEdit_1st_harm_2.setText("")
        self.lineEdit_1st_harm_2.setObjectName("lineEdit_1st_harm_2")
        self.lineEdit_num_harms_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_num_harms_2.setGeometry(QtCore.QRect(1070, 240, 113, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_num_harms_2.setFont(font)
        self.lineEdit_num_harms_2.setText("")
        self.lineEdit_num_harms_2.setObjectName("lineEdit_num_harms_2")
        self.label_Ion_Species_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_Ion_Species_2.setGeometry(QtCore.QRect(820, 30, 181, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Ion_Species_2.setFont(font)
        self.label_Ion_Species_2.setObjectName("label_Ion_Species_2")
        self.label_num_harms_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_num_harms_2.setGeometry(QtCore.QRect(820, 240, 241, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_num_harms_2.setFont(font)
        self.label_num_harms_2.setObjectName("label_num_harms_2")
        self.lineEdit_powerscale_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_powerscale_2.setGeometry(QtCore.QRect(1070, 140, 113, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_powerscale_2.setFont(font)
        self.lineEdit_powerscale_2.setText("")
        self.lineEdit_powerscale_2.setObjectName("lineEdit_powerscale_2")
        self.label_genray_filepath_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_genray_filepath_2.setGeometry(QtCore.QRect(820, 90, 201, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_genray_filepath_2.setFont(font)
        self.label_genray_filepath_2.setObjectName("label_genray_filepath_2")
        self.lineEdit_eqdsk_filepath_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_eqdsk_filepath_3.setGeometry(QtCore.QRect(1860, 90, 500, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_eqdsk_filepath_3.setFont(font)
        self.lineEdit_eqdsk_filepath_3.setText("")
        self.lineEdit_eqdsk_filepath_3.setObjectName("lineEdit_eqdsk_filepath_3")
        self.label_powerscale_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_powerscale_3.setGeometry(QtCore.QRect(1610, 140, 201, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_powerscale_3.setFont(font)
        self.label_powerscale_3.setObjectName("label_powerscale_3")
        self.label_1st_harm_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_1st_harm_3.setGeometry(QtCore.QRect(1610, 190, 251, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_1st_harm_3.setFont(font)
        self.label_1st_harm_3.setObjectName("label_1st_harm_3")
        self.lineEdit_1st_harm_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_1st_harm_3.setGeometry(QtCore.QRect(1860, 190, 113, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_1st_harm_3.setFont(font)
        self.lineEdit_1st_harm_3.setText("")
        self.lineEdit_1st_harm_3.setObjectName("lineEdit_1st_harm_3")
        self.lineEdit_num_harms_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_num_harms_3.setGeometry(QtCore.QRect(1860, 240, 113, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_num_harms_3.setFont(font)
        self.lineEdit_num_harms_3.setText("")
        self.lineEdit_num_harms_3.setObjectName("lineEdit_num_harms_3")
        self.label_Ion_Species_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_Ion_Species_3.setGeometry(QtCore.QRect(1610, 30, 181, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Ion_Species_3.setFont(font)
        self.label_Ion_Species_3.setObjectName("label_Ion_Species_3")
        self.label_num_harms_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_num_harms_3.setGeometry(QtCore.QRect(1610, 240, 241, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_num_harms_3.setFont(font)
        self.label_num_harms_3.setObjectName("label_num_harms_3")
        self.lineEdit_powerscale_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_powerscale_3.setGeometry(QtCore.QRect(1860, 140, 113, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_powerscale_3.setFont(font)
        self.lineEdit_powerscale_3.setText("")
        self.lineEdit_powerscale_3.setObjectName("lineEdit_powerscale_3")
        self.label_genray_filepath_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_genray_filepath_3.setGeometry(QtCore.QRect(1610, 90, 201, 29))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_genray_filepath_3.setFont(font)
        self.label_genray_filepath_3.setObjectName("label_genray_filepath_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RF GUI"))
        self.label_genray_filepath.setText(_translate("MainWindow", "Filepath"))
        self.label_powerscale.setText(_translate("MainWindow", "Powerscale"))
        self.label_1st_harm.setText(_translate("MainWindow", "1st Damping Harmonic"))
        self.label_num_harms.setText(_translate("MainWindow", "Number of Harmonics"))
        self.label_Ion_Species_1.setText(_translate("MainWindow", "Ion Species 1"))
        self.pushButton_quit.setText(_translate("MainWindow", "&Quit"))
        self.pushButton_save_data_quit.setText(_translate("MainWindow", "&Save Data and Quit"))
        self.pushButton_save_data.setText(_translate("MainWindow", "&Save Data"))
        self.label_powerscale_2.setText(_translate("MainWindow", "Powerscale"))
        self.label_1st_harm_2.setText(_translate("MainWindow", "1st Damping Harmonic"))
        self.label_Ion_Species_2.setText(_translate("MainWindow", "Ion Species 2"))
        self.label_num_harms_2.setText(_translate("MainWindow", "Number of Harmonics"))
        self.label_genray_filepath_2.setText(_translate("MainWindow", "Filepath"))
        self.label_powerscale_3.setText(_translate("MainWindow", "Powerscale"))
        self.label_1st_harm_3.setText(_translate("MainWindow", "1st Damping Harmonic"))
        self.label_Ion_Species_3.setText(_translate("MainWindow", "Ion Species 3"))
        self.label_num_harms_3.setText(_translate("MainWindow", "Number of Harmonics"))
        self.label_genray_filepath_3.setText(_translate("MainWindow", "Filepath"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

